{ pkgs,
  lib,
  ...
}:
{
  programs.zed-editor = {
    enable = true;
    package = pkgs.zed-editor;

    extensions =
      [
        # Matugen theme — generated by matugen to ~/.config/zed/themes/matugen.json
        # User must select "Matugen Dark" or "Matugen Light" after first matugen run
      ]
      ++ [ "nix" "toml" "html" "opencode" ];

    userSettings = {
      theme = {
        # Will be updated to "Matugen Dark"/"Matugen Light" once matugen runs
        mode = "system";
        dark = "Matugen Dark";
        light = "Matugen Light";
      };

      base_keymap = "VSCode";

      vim_mode = false;

      ui_font_size = 16;
      buffer_font_family = "JetBrainsMono Nerd Font";
      buffer_font_size = 14;

      autosave = "on_focus_change";

      format_on_save = "on";

      terminal = {
        shell = {
          program = "${lib.getExe pkgs.fish}";
        };
        font_family = "JetBrainsMono Nerd Font";
        font_size = 13;
      };

      languages = {
        Nix = {
          language_servers = [ "nixd" "!nil" ];
          formatter = {
            external = {
              command = "${pkgs.nixpkgs-fmt}/bin/nixpkgs-fmt";
              arguments = [ ];
            };
          };
        };
      };

      telemetry = {
        diagnostics = false;
        metrics = false;
      };
    };
  };
}
