{ pkgs, ... }:
{
  # mangowc — Lightweight Wayland compositor based on dwl
  # Config: ~/.config/mango/config.conf  (source= for sub-files)
  # Keybindings mirror Hyprland: SUPER modifier, ASWD focus/move
  home.packages = with pkgs; [
    mangowc
    xdg-desktop-portal-wlr
    zenity
  ];

  # ── Main mango config ────────────────────────────────────────────────────
  home.file.".config/mango/config.conf".text = ''
    # ── Environment ──────────────────────────────────────────────────────────
    env=QT_QPA_PLATFORMTHEME,qt6ct
    env=QT_STYLE_OVERRIDE,kvantum
    env=NIXOS_OZONE_WL,1

    # ── Input ────────────────────────────────────────────────────────────────
    input {
      kb_layout=us
      follow_mouse=1
      touchpad {
        natural_scroll=yes
        tap=yes
        disable_while_typing=yes
      }
    }

    # ── Appearance ───────────────────────────────────────────────────────────
    general {
      gaps_in=4
      gaps_out=8
      border_size=2
      layout=tile
    }

    # ── Matugen colors ───────────────────────────────────────────────────────
    # Generated by: matugen image <wallpaper>
    source=~/.config/mango/matugen-colors.conf

    # ── Startup ──────────────────────────────────────────────────────────────
    exec-once=fcitx5
    exec-once=dms run

    # ── DMS-managed sources ──────────────────────────────────────────────────
    # Auto-generated by DMS: outputs, layout, colors
    source=~/.config/mango/dms/outputs.conf
    source=~/.config/mango/dms/layout.conf
    source=~/.config/mango/dms/colors.conf

    # ── Keybindings ──────────────────────────────────────────────────────────
    # All bindings mirror Hyprland equivalents as closely as mango allows.

    # ── Applications ─────────────────────────────────────────────────────────
    # Hyprland: bind=$mod, Return, exec, ghostty
    bind=SUPER,Return,spawn,ghostty
    # Hyprland: bind=$mod, B, exec, brave
    bind=SUPER,B,spawn,brave
    # Hyprland: bind=$mod, Space, exec, dms ipc call spotlight toggle
    bind=SUPER,Space,spawn_shell,dms ipc call spotlight toggle

    # ── Window management ─────────────────────────────────────────────────────
    # Hyprland: bind=$mod, Q, hy3:killactive
    bind=SUPER,Q,killclient
    # Hyprland: bind=$mod, F, fullscreen, 1  (maximize)
    bind=SUPER,F,togglemaximizescreen
    # Hyprland: bind=$mod SHIFT, F, fullscreen  (true fullscreen)
    bind=SUPER+SHIFT,F,togglefullscreen
     # Hyprland: bind=$mod, M, exit with confirm
    bind=SUPER,M,spawn_shell,zenity --question --text='Exit mango?' --title='Confirm' && mmsg -c quit
    # Hyprland: bind=$mod, L, exec, dms ipc lock lock
    bind=SUPER,L,spawn_shell,dms ipc lock lock
    # Hyprland: bind=$mod CTRL, S, exec, dms screenshot
    bind=SUPER+CTRL,S,spawn_shell,dms screenshot
    # Hyprland: bind=$mod, Tab, hyprexpo:expo, toggle  → overview
    bind=SUPER,Tab,toggleoverview

    # ── Focus (ASWD) ──────────────────────────────────────────────────────────
    # Hyprland: bind=$mod, A/D/W/S, hy3:movefocus, l/r/u/d
    bind=SUPER,A,focusdir,left
    bind=SUPER,D,focusdir,right
    bind=SUPER,W,focusdir,up
    bind=SUPER,S,focusdir,down

    # ── Move windows (SHIFT+ASWD) ─────────────────────────────────────────────
    # Hyprland: bind=$mod SHIFT, A/D/W/S, hy3:movewindow, l/r/u/d
    bind=SUPER+SHIFT,A,exchange_client,left
    bind=SUPER+SHIFT,D,exchange_client,right
    bind=SUPER+SHIFT,W,exchange_client,up
    bind=SUPER+SHIFT,S,exchange_client,down

    # ── Resize (ALT+ASWD) ────────────────────────────────────────────────────
    # Hyprland: bind=$mod ALT, A/D/W/S, resizeactive, ±10 0 / 0 ±10
    bind=SUPER+ALT,A,resizewin,-10,0
    bind=SUPER+ALT,D,resizewin,10,0
    bind=SUPER+ALT,W,resizewin,0,-10
    bind=SUPER+ALT,S,resizewin,0,10

    # ── Tab / group navigation ────────────────────────────────────────────────
    # Hyprland: bind=$mod, comma/period, hy3:focustab, l/r, wrap
    bind=SUPER,comma,focusstack,prev
    bind=SUPER,period,focusstack,next

    # ── Layout split ─────────────────────────────────────────────────────────
    # Hyprland: bind=$mod, H, hy3:makegroup, h  → vertical split (more masters)
    bind=SUPER,H,incnmaster,+1
    # Hyprland: bind=$mod, V, hy3:makegroup, v  → reduce masters
    bind=SUPER,V,incnmaster,-1
    # Hyprland: bind=$mod, C, hy3:changegroup, opposite  → center layout
    bind=SUPER,C,switch_layout

    # ── Tags 1–10 (mango uses tags, not workspaces) ───────────────────────────
    # Hyprland: bind=$mod, 1-9, workspace, 1-9
    bind=SUPER,1,view,1
    bind=SUPER,2,view,2
    bind=SUPER,3,view,3
    bind=SUPER,4,view,4
    bind=SUPER,5,view,5
    bind=SUPER,6,view,6
    bind=SUPER,7,view,7
    bind=SUPER,8,view,8
    bind=SUPER,9,view,9
    # Hyprland: bind=$mod, 0, workspace, 10
    bind=SUPER,0,view,0

    # Hyprland: bind=$mod SHIFT, 1-9, hy3:movetoworkspace, 1-9
    bind=SUPER+SHIFT,1,tag,1
    bind=SUPER+SHIFT,2,tag,2
    bind=SUPER+SHIFT,3,tag,3
    bind=SUPER+SHIFT,4,tag,4
    bind=SUPER+SHIFT,5,tag,5
    bind=SUPER+SHIFT,6,tag,6
    bind=SUPER+SHIFT,7,tag,7
    bind=SUPER+SHIFT,8,tag,8
    bind=SUPER+SHIFT,9,tag,9
    # Hyprland: bind=$mod SHIFT, 0, hy3:movetoworkspace, 10
    bind=SUPER+SHIFT,0,tag,0

    # Hyprland: bind=, mouse:275/276, workspace, e+1/e-1
    bind=NONE,mouse:275,viewtoright
    bind=NONE,mouse:276,viewtoleft
  '';

  # ── default.nix entry point ──────────────────────────────────────────────
}
