{ pkgs, ... }:
{
  home.packages = [ pkgs.foot ];

  # foot.ini generated by matugen (foot.ini template)
  # Main config loads the theme
  home.file.".config/foot/foot.ini".text = ''
    font=JetBrainsMono Nerd Font:size=13
    pad=8x8
    
    [main]
    term=xterm-256color
    
    [mouse]
    hide-when-typing=yes
    
    include=~/.config/foot/theme.ini
  '';
}