{ pkgs, ... }:
{
  home.packages = [ pkgs.dunst ];

  # dunstrc is fully generated by matugen (dunstrc-colors template).
  # The file at ~/.config/dunst/dunstrc will be created/updated on each
  # `matugen image <wallpaper>` run, with post_hook = "dunstctl reload".
  #
  # We create the config directory and a stub so dunst starts even before
  # the first matugen run.
  home.file.".config/dunst/dunstrc" = {
    # Only write this fallback if matugen hasn't generated it yet.
    # Once matugen runs, it will overwrite this file.
    force = false;
    text = ''
      [global]
      monitor = 0
      follow = none
      width = 400
      height = 400
      origin = top-right
      offset = 10x40
      notification_limit = 5
      progress_bar = true
      progress_bar_height = 10
      frame_width = 1
      corner_radius = 8
      font = JetBrainsMono Nerd Font 11
      markup = full
      format = "<b>%s</b>\n%b"
      icon_position = left
      min_icon_size = 0
      max_icon_size = 32
      mouse_left_click = close_current
      mouse_middle_click = do_action, close_current
      mouse_right_click = close_all

      [urgency_low]
      timeout = 3
      background = "#1e1e2e"
      foreground = "#cdd6f4"

      [urgency_normal]
      timeout = 6
      background = "#1e1e2e"
      foreground = "#cdd6f4"

      [urgency_critical]
      timeout = 0
      background = "#1e1e2e"
      foreground = "#f38ba8"
    '';
  };
}
