{ pkgs, ... }:
{
  home.packages = [ pkgs.dunst ];

  # dunstrc is fully generated by matugen (dunstrc-colors template).
  # No stub file here — matugen will create it directly.
  # Ensure the directory exists for matugen to write into.
  home.file.".config/dunst/.keep".text = "";
}
