{ ... }:
{
  programs.ghostty = {
    enable = true;
    enableBashIntegration = true;
    enableFishIntegration = true;
    settings = {
      font-family = "JetBrainsMono Nerd Font";
      font-size = 13;
      window-decoration = "server";
      # Theme generated by matugen → ~/.config/ghostty/themes/Matugen
      # post_hook in matugen config sends SIGUSR2 to reload live
      theme = "Matugen";
    };
  };
}
