{ ... }:
{
  programs.zellij = {
    enable = true;
    settings = {
      # Theme generated by matugen → ~/.config/zellij/themes/matugen.kdl
      theme = "matugen";
      # No inline theme definitions — all colors from matugen
    };
  };
}
