{ ... }:
{
  programs.fish = {
    enable = true;
    interactiveShellInit = ''
      # Initialize starship (config generated by matugen)
      starship init fish | source
      # Initialize zoxide
      zoxide init fish | source
    '';
    plugins = [ ];
  };
}
