{ ... }:
{
  programs.nushell = {
    enable = true;
    envFile.text = ''
      # Initialize starship (config generated by matugen)
      let starship_cache = ($env.HOME | path join .cache/starship)
      $env.STARSHIP_CACHE = $starship_cache
      mkdir $starship_cache
      let starship_init_file = ($starship_cache | path join init.nu)
      starship init nu | save --force $starship_init_file
    '';
    loginFile.text = ''
      source ($env.STARSHIP_CACHE | path join init.nu)
    '';
  };
}
