{ ... }:
{
  # starship.toml is fully generated by matugen (starship-colors.toml template).
  # We only enable the integrations here — do NOT set settings, as they would
  # conflict with / overwrite the matugen-generated ~/.config/starship.toml.
  programs.starship = {
    enable = true;
    enableFishIntegration = true;
    enableNushellIntegration = true;
  };
}
