{ pkgs, ... }:
{
  programs.firefox = {
    enable = true;
    package = pkgs.firefox;
    
    profiles.default = {
      id = 0;
      name = "default";
      isDefault = true;
      
      # Enable userChrome.css for matugen theme
      settings = {
        "toolkit.legacyUserProfileCustomizations.stylesheets" = true;
        "userChrome.theme-material" = true;
      };
      
      # userChrome.css will be generated by matugen
      # Path: ~/.mozilla/firefox/<profile>/chrome/userChrome.css
    };
  };

  # Matugen generates userChrome.css to this location
  # User needs to link/copy it to firefox profile chrome directory
}