{ pkgs, ... }:
{
  home.packages = with pkgs; [
    vivaldi
    vivaldi-ffmpeg-codecs
  ];

  # Vivaldi custom CSS is generated by matugen to ~/.config/vivaldi/custom.css
  # To enable: Vivaldi Settings → Appearance → Themes → Edit → Enable Custom CSS
}