{ pkgs, lib, ... }:
{
  # niri compositor — home-manager 25.11 does not have wayland.windowManager.niri,
  # so we manage the package and config file directly.
  home.packages = with pkgs; [
    niri
    xdg-desktop-portal-gnome  # portal support for niri
  ];

  # Main niri config — KDL format.
  # Matugen colors included at the bottom via activation script.
  home.file.".config/niri/config.kdl".text = ''
    // ── Input ──────────────────────────────────────────────────────────────
    input {
      keyboard {
        xkb { layout "us"; }
      }
      touchpad {
        tap
        natural-scroll
        dwt
      }
      warp-mouse-to-focus
      focus-follows-mouse
    }

    // ── Layout ─────────────────────────────────────────────────────────────
    layout {
      gaps 8

      preset-column-widths {
        proportion 0.33333
        proportion 0.5
        proportion 0.66667
      }

      default-column-width { proportion 0.5; }

      // Fallback colors overridden by matugen-colors.kdl include below
      focus-ring {
        width 2
        active-color "#7fc8ff"
        inactive-color "#505050"
      }

      border { off; }
    }

    // ── Animations ─────────────────────────────────────────────────────────
    animations { }

    // ── Startup ────────────────────────────────────────────────────────────
    spawn-at-startup "fcitx5"
    spawn-at-startup "dms" "run"

    // ── Environment ────────────────────────────────────────────────────────
    environment {
      DISPLAY ":0"
      QT_QPA_PLATFORMTHEME "qt6ct"
      QT_STYLE_OVERRIDE "kvantum"
    }

    // ── Keybindings ────────────────────────────────────────────────────────
    binds {
      // Applications
      Mod+Return { spawn "ghostty"; }
      Mod+B      { spawn "brave"; }
      Mod+Space  { spawn "dms" "ipc" "call" "spotlight" "toggle"; }

      // Window management
      Mod+Q       { close-window; }
      Mod+F       { maximize-column; }
      Mod+Shift+F { fullscreen-window; }
      Mod+C       { center-column; }

      // Focus (ASWD — matches Hyprland layout)
      Mod+A { focus-column-left; }
      Mod+D { focus-column-right; }
      Mod+W { focus-window-up; }
      Mod+S { focus-window-down; }

      // Move
      Mod+Shift+A { move-column-left; }
      Mod+Shift+D { move-column-right; }
      Mod+Shift+W { move-window-up; }
      Mod+Shift+S { move-window-down; }

      // Resize
      Mod+Alt+A { set-column-width "-10%"; }
      Mod+Alt+D { set-column-width "+10%"; }
      Mod+Alt+W { set-window-height "-10%"; }
      Mod+Alt+S { set-window-height "+10%"; }

      // Workspaces
      Mod+1 { focus-workspace 1; }
      Mod+2 { focus-workspace 2; }
      Mod+3 { focus-workspace 3; }
      Mod+4 { focus-workspace 4; }
      Mod+5 { focus-workspace 5; }
      Mod+6 { focus-workspace 6; }
      Mod+7 { focus-workspace 7; }
      Mod+8 { focus-workspace 8; }
      Mod+9 { focus-workspace 9; }
      Mod+Shift+1 { move-column-to-workspace 1; }
      Mod+Shift+2 { move-column-to-workspace 2; }
      Mod+Shift+3 { move-column-to-workspace 3; }
      Mod+Shift+4 { move-column-to-workspace 4; }
      Mod+Shift+5 { move-column-to-workspace 5; }
      Mod+Shift+6 { move-column-to-workspace 6; }
      Mod+Shift+7 { move-column-to-workspace 7; }
      Mod+Shift+8 { move-column-to-workspace 8; }
      Mod+Shift+9 { move-column-to-workspace 9; }

      // Screenshot & session
      Mod+Ctrl+S { spawn "dms" "screenshot"; }
      Mod+M { spawn "sh" "-c" "niri msg action quit"; }
      Mod+L { spawn "dms" "ipc" "lock" "lock"; }
    }

    // ── Matugen dynamic colors ──────────────────────────────────────────────
    // Generated by: matugen image <wallpaper>
    // File: ~/.config/niri/matugen-colors.kdl
    include "matugen-colors.kdl"
  '';
}
