{ pkgs, ... }:
{
  programs.yazi = {
    enable = true;

    settings = {
      manager = {
        ratio = [ 1 3 4 ];
        sort_by = "alphabetical";
        sort_sensitive = false;
        sort_reverse = false;
        sort_dir_first = true;
        linemode = "size";
        show_hidden = false;
        show_symlink = true;
      };
      preview = {
        tab_size = 2;
        max_width = 1200;
        max_height = 900;
        cache_dir = "";
        image_filter = "triangle";
        image_quality = 75;
        sixel_fraction = 15;
        ueberzug_scale = 1;
        ueberzug_offset = [ 0 0 0 0 ];
      };
    };

    keymap = {
      manager.prepend_keymap = [
        { on = "<Tab>"; run = "arrow 1"; desc = "Move cursor down"; }
        { on = "<S-Tab>"; run = "arrow -1"; desc = "Move cursor up"; }
        { on = "T"; run = "tab_create --current"; desc = "Create a new tab with cwd"; }
      ];
    };

    # theme.toml is generated by matugen — do not declare here
  };

  # Yazi dependencies for previews
  home.packages = with pkgs; [
    ffmpegthumbnailer   # video thumbnails
    unar                # archive preview
    jq                  # JSON preview
    poppler-utils       # PDF preview
    fd                  # file search
  ];
}
