{ pkgs, ... }:
{
  programs.helix = {
    enable = true;

    # Theme fully generated by matugen → ~/.config/helix/themes/matugen.toml
    settings = {
      theme = "matugen";
      editor = {
        line-number = "relative";
        auto-save = true;
        completion-trigger-len = 1;
        color-modes = true;
        cursor-shape = {
          insert = "bar";
          normal = "block";
          select = "underline";
        };
        indent-guides.render = true;
        lsp.display-messages = true;
      };
    };

    languages = {
      language-server.nixd = {
        command = "nixd";
      };
      language = [
        {
          name = "nix";
          auto-format = true;
          formatter = {
            command = "${pkgs.nixpkgs-fmt}/bin/nixpkgs-fmt";
          };
          language-servers = [ "nixd" ];
        }
      ];
    };
  };
}
