{ pkgs, ... }:
{
  programs.micro = {
    enable = true;
    settings = {
      # Colors come from matugen-generated ~/.config/micro/colorschemes/matugen.micro
      colorscheme = "matugen";
      autoindent  = true;
      tabsize     = 2;
      tabstospaces = true;
      ruler       = true;
      softwrap    = true;
      mouse       = true;
      savecursor  = true;
      saveundo    = true;
      # Statusline info
      statusformatr = "$(filename) $(modified) - $(line)/$(lines) $(col)";
      # Use JetBrainsMono Nerd Font glyphs
      sucmd = "sudo";
    };
  };

  # matugen.micro is generated by matugen (micro template).
  # We provide a stub so micro starts without error before the first matugen run.
  home.file.".config/micro/colorschemes/matugen.micro" = {
    force = false;   # don't overwrite matugen-generated file
    text = ''
      # Placeholder until matugen generates this file.
      # Run: matugen image <wallpaper-path>
      color-link default "#cdd6f4,#1e1e2e"
      color-link comment "#6c7086"
      color-link identifier "#89b4fa"
      color-link constant "#a6e3a1"
      color-link constant.string "#a6e3a1"
      color-link type "#89b4fa"
      color-link statement "#cba6f7"
      color-link error "bold #f38ba8"
      color-link statusline "#1e1e2e,#89b4fa"
    '';
  };
}
