{ pkgs, ... }:
{
  programs.micro = {
    enable = true;
    settings = {
      # Colors come from matugen-generated ~/.config/micro/colorschemes/matugen.micro
      colorscheme = "matugen";
      autoindent  = true;
      tabsize     = 2;
      tabstospaces = true;
      ruler       = true;
      softwrap    = true;
      mouse       = true;
      savecursor  = true;
      saveundo    = true;
      # Statusline info
      statusformatr = "$(filename) $(modified) - $(line)/$(lines) $(col)";
      # Use JetBrainsMono Nerd Font glyphs
      sucmd = "sudo";
    };
  };

  # matugen.micro is generated by matugen (micro template).
  # No stub file here — matugen will create it directly.
}
