{ pkgs, lib, ... }:
{
  home.packages = with pkgs; [
    kdePackages.qtstyleplugin-kvantum
    libsForQt5.qt5ct
    kdePackages.qt6ct
    adwaita-qt
    adwaita-qt6
  ];

  # qt5ct config — points to matugen-generated color scheme
  home.file.".config/qt5ct/qt5ct.conf".text = ''
    [Appearance]
    color_scheme_path=${builtins.getEnv "HOME"}/.config/qt5ct/colors/matugen.conf
    custom_palette=true
    icon_theme=Papirus
    style=kvantum-dark

    [Fonts]
    fixed="JetBrainsMono Nerd Font,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
    general="Noto Sans CJK SC,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
  '';

  # qt6ct config — points to matugen-generated color scheme
  home.file.".config/qt6ct/qt6ct.conf".text = ''
    [Appearance]
    color_scheme_path=${builtins.getEnv "HOME"}/.config/qt6ct/colors/matugen.conf
    custom_palette=true
    icon_theme=Papirus
    style=kvantum-dark

    [Fonts]
    fixed="JetBrainsMono Nerd Font,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
    general="Noto Sans CJK SC,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
  '';

  # kvantum.kvconfig is written by sys/matugen/matugen.nix (theme=matugen)
  # The kvantum theme files (kvconfig + svg) are generated by matugen templates
}
